export const RondType = [
  { name: "NORMAL", title: "معمولی" },
  { name: "SEVENRY", title: "رند ۷ رقم یکی" },
  { name: "SEXRYE", title: "رند ۶ رقم یکی از اخر" },
  { name: "SEXRYS", title: "رند ۶ رقم یکی از اول" },
  { name: "MELLION", title: "رند میلیونی" },
  { name: "TENTE", title: "رند ده هزاری از اخر" },
  { name: "TENTS", title: "رند ده هزاری از اول" },
  { name: "THREEPE", title: "رند ۳ جفت از اخر" },
  { name: "THREEPS", title: "رند ۳ جفت از اول" },
  { name: "TOWR", title: "رند متشکل از دو رقم" },
  { name: "FIVERE", title: "رند ۵ رقم یکی از اخر" },
  { name: "FIVERS", title: "رند ۵ رقم یکی از اول" },
  { name: "SADDARSADI", title: "رند صد درصدی" },
  { name: "GOFTARI", title: "رند گفتاری" },
  { name: "TE", title: "رند هزاری از اخر" },
  { name: "TS", title: "رند هزاری از اول" },
  { name: "FOURRE", title: "رند ۴ رقم یکی از اخر" },
  { name: "FOURRS", title: "رند ۴ رقم یکی از اول" },
  { name: "FOURRM", title: "رند ۴ رقم یکی از وسط" },
  { name: "TENTENE", title: "رند ده دهی از اخر" },
  { name: "TENTENS", title: "رند ده دهی از اول" },
  { name: "THREEPELE", title: "رند ۳ پله" },
  { name: "PPE", title: "رند جفت جفت از اخر" },
  { name: "PPS", title: "رند جفت جفت از اول" },
  { name: "THREEYS", title: "رند ۳ رقم یکی از اول" },
  { name: "IPS", title: "رند تکرار پیش شماره" },
  { name: "TARAZOEI", title: "رند ترازویی" },
  { name: "PELEIE", title: "رند پله‌ای از اخر" },
  { name: "PELEIS", title: "رند پله‌ای از اول" },
  { name: "THREERE", title: "رند ۳ رقم یکی از اخر" },
  { name: "TARTIBIEND", title: "رند ترتیبی از اخر" },
  { name: "TARTIBISTART", title: "رند ترتیبی از اول" },
  { name: "AYNEI", title: "رند آینه‌ای" },
];
